# Generated by Django 6.1.1 on 2026-09-09 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('species', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=20, verbose_name='Espécie')),
                ('breed', models.CharField(max_length=80, verbose_name='Raça')),
                ('size', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=20, verbose_name='Porte')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='customers.customer', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['name'],
            },
        ),
    ]
